#pragma once

#define COLOR_LIGHT_YELLOW 8
#define COLOR_LIGT_YELLOW_GREEN 9
#define COLOR_PALE_GREEN 10
#define COLOR_MEDIUM_SPRING_GREEN 11
#define COLOR_SPRING_GREEN 12
#define COLOR_GREEN_YELLOW 13
#define COLOR_LAWN_GREEN 14
#define COLOR_LIME 15
#define COLOR_LIME_GREEN 16
#define COLOR_NEON_GREEN 17
#define COLOR_MINT 18

enum class Direction {
    UP,
    DOWN,
    LEFT,
    RIGHT
};
